use DIRECT_EXCHANGE;

ALTER TABLE ACCOUNT
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE OFFER
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE COUNTER_OFFER
ADD FOREIGN KEY (OfferID)
  REFERENCES OFFER (OfferID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
    
ALTER TABLE COUNTER_OFFER
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE EXCHANGE_TRANSACTION
ADD FOREIGN KEY (OfferID)
  REFERENCES OFFER (OfferID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE EXCHANGE_RATE
ADD COLUMN Country varchar(30);

ALTER TABLE TRANSACTION_USER_MAP
ADD FOREIGN KEY (UserID)
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE TRANSACTION_USER_MAP
ADD FOREIGN KEY (TransactionID)
  REFERENCES EXCHANGE_TRANSACTION (TransactionID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;