use DIRECT_EXCHANGE;

ALTER TABLE ACCOUNT
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE OFFER
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE COUNTER_OFFER
ADD FOREIGN KEY (OfferID)
  REFERENCES OFFER (OfferID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
    
ALTER TABLE COUNTER_OFFER
ADD FOREIGN KEY (UserID )
  REFERENCES SIGNUP (ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  
ALTER TABLE EXCHANGE_TRANSACTION
ADD FOREIGN KEY (OfferID)
  REFERENCES OFFER (OfferID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;